name: Deploy ContosoAds to Azure Container Apps
concurrency: contosoads-deploy-${{ github.ref }}

on:    
  push:
    branches:
      - deploy
    paths:
      - 'components/**'
      - 'deploy/**'
      - 'src/**'
      - '.github/workflows/**'

env:
    # Specify your resource group's name
    RESOURCE_GROUP: contosoads

    # Specify your preferred region
    LOCATION: northeurope
  
    # Specify login credentials for PostgreSQL
    DB_LOGIN: contosoads
    
    # Specify your GitHub repo to source the DB migration script from (must be public)
    REPOSITORY: 'https://github.com/joergjo/contosoads-containerapp.git'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch 
        uses: actions/checkout@v3
        
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SPN }}

      - name: Create resource group
        uses: azure/CLI@v1
        with:
          inlineScript: >
            echo "Creating resource group in Azure"
            echo "Executing 'az group create -l ${{ env.LOCATION }} -n ${{ env.RESOURCE_GROUP }}'"
            
            az group create -l ${{ env.LOCATION }} -n ${{ env.RESOURCE_GROUP }}

      - name: Deploy Bicep template  
        uses: azure/arm-deploy@v1
        with:
          deploymentName: contosoads-${{ github.run_number }}-${{ github.run_attempt }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: ./deploy/main.bicep
          parameters: postgresLogin=${{ env.DB_LOGIN }} postgresLoginPassword=${{ secrets.DB_PWD }} repository=${{ env.REPOSITORY }}
